### ISSUE TITLE
AttributeError: module 're' has no attribute 'Pattern'

### ISSUE THREAD

**Issue by dh12306** [hscspring/pnlp#1]
python version：3.6.9  @hscspring 
from pnlp import piop
  File "D:\rj\ana3\lib\site-packages\pnlp\__init__.py", line 3, in <module>
    from .pcut import cut_sentence, cut_zhchar, cut_part, combine_bucket
  File "D:\rj\ana3\lib\site-packages\pnlp\pcut.py", line 81, in <module>
    with_offset: bool = False) -> list:
AttributeError: module 're' has no attribute 'Pattern'

**Comment by hscspring** [comment]
`re.Pattern` 是 re 模块内置的。
我怀疑是 python 版本的问题。抱歉忘记说明了，python3.7 以上。
